blueprint:
  name: Cover Automation
  description: Automatically managed "day" cover based on illuminance, Alarm mode and sun
  domain: automation
  source_url: https://github.com/Xavieto/hablueprints/blob/main/cover_automation.yaml
  input:
    cover_target:
      name: Cover
      selector:
        target:
          entity:
            domain: cover
    alarm_entity:
      name: Alarm
      selector:
        entity:
          domain: alarm_control_panel
    illuminance_entity:
      name: Illuminance Sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    illuminance_level:
      name: Illuminance Level
      description: Higher level of luminance to met the trigger condition (cover will be closed below the value).
      default: 10
      selector:
        number:
          min: 0
          max: 60000
          unit_of_measurement: lux

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input alarm_entity
    from: null
    to: null
  - platform: sun
    event: sunrise
    offset: "-00:10:00"
  - platform: sun
    event: sunset
    offset: "+00:10:00"
  - platform: numeric_state
    entity_id: !input illuminance_entity
    below: !input illuminance_level
  - platform: numeric_state
    entity_id: !input illuminance_entity
    above: !input illuminance_level
condition: []
action:
  - if:
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: !input illuminance_entity
            above: !input illuminance_level
          - condition: sun
            after: sunrise
            before: sunset
            before_offset: "-00:10:00"
            after_offset: "+00:10:00"
          - condition: not
            conditions:
              - condition: state
                entity_id: !input alarm_entity
                state: armed_night
    then:
      - service: cover.open_cover
        metadata: {}
        data: {}
        target:
          entity_id: !input cover_target
    else:
      - service: cover.close_cover
        metadata: {}
        data: {}
        target:
          entity_id: !input cover_target